version: '3.7'
services:
  db:
    image: postgres

  web: 
    build: .
    volumes: 
      - .:/myapp
    ports: 
      - "3000:3000"
    depends_on:
      - db
    tty: true
    stdin_open: true
    command: bundle exec rails s -p 3000 -b 0.0.0.0

  webpack-dev:
    image: pomodoro_arcade_web
    depends_on:
      - web 
    volumes:
      - .:/myapp
    ports:
      - "3035:3035"
    #command: ./bin/webpack-dev-server --inline true --hot true --port 8080 --public 0.0.0.0:8080
    command: ./bin/webpack-dev-server --inline true --hot true --public 0.0.0.0:3035
