FROM node:8.12
#FROM node:8.12-alpine

#For alpine
#RUN apk add yarn
#For debian
RUN apt-get update -qq && apt-get install -y build-essential apt-utils apt-transport-https
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
RUN apt-get update -qq && apt-get install -y yarn

ENV APP_HOME /myapp
RUN mkdir -p $APP_HOME
WORKDIR $APP_HOME
COPY package.json /myapp
COPY yarn.lock /myapp
RUN yarn install
WORKDIR $APP_HOME

CMD echo "hello webpack"
